### ISSUE TITLE
Crash on Start up with BetterNetherX

### ISSUE THREAD

**Issue by Talan67** [Sinytra/Connector#13]
### Describe the bug

Crash on Start up

### Steps to reproduce

1. Install Connector, Forgified Fabric API for Forge Loader
2. Download Fabric mods and install them in the Forge mods folder
3. Launch Forge
4. Crash

### Logs

https://pastebin.com/NPacdw3k

### Additional context

Forge Version 47.3.43

Mods:
Connector-1.0.0-beta+1.20.1-full
fabric-api-0.86.1+1.7.2+1.20.1
better-nether-9.0.9
bclib-3.0.13

**Comment by Talan67** [comment]
I'm aware this might be ambitious to expect something as demanding and complex to work on forge with connector right away but at least we can see if its possible.

**Comment by Su5eD** [comment]
This should be fixed in `1.0.0-beta.2` now. You'll also need to update FFAPI to `0.86.1+1.8.0+1.20.1`, which fixes an issue with missing AWs.

I was able to get the mod up and running, everything seems to work fine.

| ![](https://github.com/Sinytra/Connector/assets/51261569/3ef973d5-6530-42ef-93eb-a0e6fde3fbe3) | ![](https://github.com/Sinytra/Connector/assets/51261569/fb4b7f2f-4845-4008-b4fd-dce23719bc9f) |
|--------|--------|

I also decided to give BetterEnd (installed along with better nether) a shot, and it worked fine, too. It's worth noting I had to generate a fresh world to get it to run.

<img src="https://github.com/Sinytra/Connector/assets/51261569/aab3358c-62fe-4bec-8a95-998cd29bd5b0" alt="alt text" width="50%" height="50%">

**Comment by Talan67** [comment]
Still unable to get it to work, could you tell me what forge version you are using?

**Comment by Talan67** [comment]
yeah still crashing, fresh profile with all mods up to date

**Comment by Talan67** [comment]
What mod versions are you running?

heres log: 
[latest.log](https://github.com/Sinytra/Connector/files/12303538/latest.log)

**Comment by Su5eD** [comment]
Getting the same crash now outside the dev env. I'll look into it.

**Comment by Su5eD** [comment]
Okay, try using these builds.  
- [Connector](https://github.com/Sinytra/Connector/suites/14954200366/artifacts/852775615) - extract `Connector-1.0.0-beta.3+1.20.1-full.jar` from the zip
- [Forgified Fabric API](https://github.com/Sinytra/ForgifiedFabricAPI/suites/14954101153/artifacts/852778851) - extract `fabric-api-0.86.1+1.8.1+1.20.1.jar` from the zip

**Comment by Talan67** [comment]
Got another issue though its some other mod conflict on a bigger mod list, Im gonna skim through the list until I find the issue then send you the logs, if thats alright.

So far got rubidium, modernfix, ferritecore, goal optimiser and redirectioner playing nice with forgified fabric.

**Comment by Su5eD** [comment]
That's good to hear, I'll move on with the release. Feel free to open an issue once you've identified the problematic mod.
