### ISSUE TITLE
[Crash] Frostiful / Thermoo classexceptions and mod-incompat

### ISSUE THREAD

**Issue by Cixon** [Sinytra/Connector#169]
### Mod Name

Frostiful

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/frostiful

### Describe the bug

Crashed client when entering a Betterend biome

### Steps to reproduce

1. Install Sinytra
2. Install Frostiful, Thermoo and Cloth Config API [fabric]
3. Install Betterend + BCLib
4. Enter the end and locate any betterend to TP.
5. See Results

Source Code for Frostiful and Thermoo:
https://github.com/TheDeathlyCow/frostiful
https://github.com/TheDeathlyCow/thermoo

### Logs

https://gist.github.com/Cixon/fb0aea760fe69a5561500dabb223fcb4

### Additional context

Thank you for adding compat to Midnight Controls and allowing Frostiful to load but sadly, thermoo & frostiful may need some more fixing...

Tested in a single player environment only.
_FML 47.1.3_
-
Crash report too:
[crash-2023-09-02_17.19.29-server.txt](https://github.com/Sinytra/Connector/files/12504816/crash-2023-09-02_17.19.29-server.txt)

**Comment by Cixon** [comment]
Tested the same mods on fabric mod-loader too, no problems occurred between the mods.
That tested was conducted on 0.14.22.

**Comment by Su5eD** [comment]
According to the logs, this is caused by a Connector bug that was fixed just yesterday in 83bcd99c133d8aeeb565d163b7e232230146eed3. Can you try using the latest CI [dev build](https://github.com/Sinytra/Connector/suites/15779295261/artifacts/900523165)? I did so myself and didn't run into any crashes.

**Comment by EndangeredNayla** [comment]
nope still an issue :)

https://crashy.net/11709a8c-0158-475d-b56b-c0bba0c3d973

**Comment by rainysux** [comment]
Did you try deleting the connector folder and trying again?

**Comment by Cixon** [comment]
bug eradicated in [83bcd99](https://github.com/Sinytra/Connector/commit/83bcd99c133d8aeeb565d163b7e232230146eed3).

**Comment by Cixon** [comment]
also sorry for delay, was doing a lot of things. thanks for the fix!
