### ISSUE TITLE
LambDynamicLights is incompatible with Ars Nouveau

### ISSUE THREAD

**Issue by uthw** [Sinytra/Connector#450]
### Describe the bug

When on the "joining world" screen, the game crashes if both Ars Nouveau and LambDynamicLights are present

### Steps to reproduce

1. Add Connector, FFAPI, LambDynamicLights, and Ars Nouveau + dependencies (Curios and Patchouli)
2. Load or create a world
3. Crash

### Logs

[debug.log](https://gist.github.com/uthw/6436db795a05009b9c635c641034e0d1) [crash report](https://gist.github.com/uthw/5cc04c972991526bf13eb46f1458cdfe) [latest.log](https://gist.github.com/uthw/6c1b561d75df2373d7b6ac195c8fbe35)

### Additional context

This seems to be caused by Ars Nouveau including its own dynamic lights. The game still crashes when they're disabled in the client config.

I had Connector Extras enabled and was using beta 22 built from source as in my other report

**Comment by kakashi1464** [comment]
Afaik this has been fixed in ryomic lights - https://modrinth.com/mod/ryoamiclights

**Comment by Su5eD** [comment]
Seems like not, I've tried it out and it still crashes with the same errror
> Caused by: java.lang.AbstractMethodError: Receiver class net.minecraft.client.player.LocalPlayer does not define or inherit an implementation of the resolved method 'boolean isDynamicLightEnabled()' of interface dev.lambdaurora.lambdynlights.DynamicLightSource.  
&nbsp;&nbsp;&nbsp;&nbsp;at dev.lambdaurora.lambdynlights.LambDynLights.updateTracking(LambDynLights.java:437)
&nbsp;&nbsp;&nbsp;&nbsp;at net.minecraft.world.entity.Entity.handler$zjo003$ryoamiclights$onTick(Entity.java:5131)

**Comment by RoomAlex68** [comment]
Ars Nouveau is tied to Forge Geckolib and its incompatible with Fabric Geckolib

**Comment by uthw** [comment]
Interesting. The forge port crashed with my custom pack when I tried it earlier, so I'll have to see what conflicts with it when I get home. For anyone else who has this issue, iirc Ars Nouveau lets you use a custom list of items that have dynamic lights, so you could add things to it if nothing else works.
